### ISSUE TITLE
Spongebed starla dedi bende starlıcam ben işsizim

### ISSUE THREAD

**Issue by 0xerorn** [CodAre-Development/v12tov13#1]
Başlığı oku knk.

**Nice Proje İyi çalışmalar.**

**Comment by 0xerorn** [comment]
**BU PROJEYİ STARLAMASSAN SPONGEBED SENİN EVİNE GELİP GOOGLE ARAMA GEÇMİŞİNİ HERKEZE YAYAR**

**Comment by SpongeBed81** [comment]
adam ya.
